# This is a basic workflow to help you get started with Actions

name: Migration CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop, feature/migration-test ]
  pull_request:
    branches: [ develop, feature/migration-test ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  execute_migration:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Shutdown default MySQL
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop # Shutdown the Default MySQL, "sudo" is necessary, please not remove it

      - name: Fetch initial SQL files
        run: |
          r=$(curl -I https://redmine.seichi.click/attachments/download/895/gachadata.sql | head -n 1 | awk '{print $2}')
          if [[ "$r" -ne "200" ]]; then
          echo "status: $r"
          exit 1
          fi
          wget https://redmine.seichi.click/attachments/download/895/gachadata.sql
          
          r=$(curl -I https://redmine.seichi.click/attachments/download/894/msgachadata.sql | head -n 1 | awk '{print $2}')
          if [[ "$r" -ne "200" ]]; then
          echo "status: $r"
          exit 1
          fi
          wget https://redmine.seichi.click/attachments/download/894/msgachadata.sql
          echo Initial files: fetched.
      - uses: getong/mariadb-action@v1.1
        with:
          host port: 3306 # Optional, default value is 3306. The port of host
          mariadb version: '10.1.37' # Optional, default value is "latest". The version of the MariaDB
          mysql root password: ${{ secrets.RootPassword }} # Required if "mysql user" is empty, default is empty. The root superuser password
      # Runs a set of commands using the runners shell
      - name: Apply initial SQL
        run: |
          echo Apply initial SQL: gachadata.sql...
          sudo mysql -P 3306 -h localhost -u root -p ${{ secrets.RootPassword }} < gachadata.sql
          echo Apply initial SQL: msgachadata.sql...
          sudo mysql -P 3306 -h localhost -u root -p ${{ secrets.RootPassword }} < msgachadata.sql
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
          
